### 1. 모든 경우의 수 고려
GET http://localhost/flask/recruit/filter?visa=E-9&visa=H-2&work_location=서울&work_location=인천&job_name=제조&job_name=생산&
    keyword=여자 여성 신입
Accept: application/json

{%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### 2-1. visa 0개
GET http://localhost/flask/recruit/filter?work_location=서울&work_location=인천&job_name=제조&job_name=생산&keyword=여자 여성 신입
Accept: application/json

### 2-2. visa 1개
GET http://localhost/flask/recruit/filter?visa=E-9&work_location=서울&work_location=인천&job_name=제조&job_name=생산&
    keyword=여자 여성 신입
Accept: application/json

### 3-1. work_location 0개
GET http://localhost/flask/recruit/filter?visa=E-9&job_name=제조&job_name=생산&keyword=여자 여성 신입
Accept: application/json

### 3-2. work_location 1개
GET http://localhost/flask/recruit/filter?visa=E-9&work_location=서울&job_name=제조&job_name=생산&keyword=여자 여성 신입
Accept: application/json

### 4-1. job_name 0개
GET http://localhost/flask/recruit/filter?visa=E-9&keyword=여자 여성 신입
Accept: application/json

### 4-2. job_name 1개
GET http://localhost/flask/recruit/filter?visa=E-9&work_location=서울&job_name=생산&keyword=여자 여성 신입
Accept: application/json

### 5-1. keyword 0개
GET http://localhost/flask/recruit/filter?visa=E-9&visa=H-2&work_location=서울&work_location=인천&job_name=제조&job_name=생산
Accept: application/json

### 5-2. keyword 1개
GET http://localhost/flask/recruit/filter?visa=E-9&visa=H-2&work_location=서울&work_location=인천&job_name=제조&job_name=생산&
    keyword=여자
Accept: application/json