spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri : http://kdt-please.store/login/oauth2/code/google
            scope:
              - profile
              - email

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_BUCKET_NAME}
    stack:
      auto: false
    credentials:
      secret-key: ${AWS_SECRET_KEY}
      access-key: ${AWS_ACCESS_KEY}
