name: deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  deploy_project:
    runs-on: ubuntu-latest

    # deployment
    steps:
      - uses: actions/checkout@v3

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/project-please-back/
            sudo docker rm -f $(docker ps -qa)
            docker image prune -a
            docker volume prune -a
            cat ~/project-please-back/docker-compose.yml
            docker-compose -f ~/project-please-back/docker-compose.yml up -d
