name: deployment

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  deploy_project:
    runs-on: ubuntu-latest

    # deployment
    steps:
      - uses: actions/checkout@v3

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo rm -rf project-please-back
            sudo git clone https://github.com/KDT-BokJob/project-please-back.git
            sudo cat project-please-back/docker-compose.yml
            
            sudo docker rm -f project-please-back_reverse_proxy_1
            sudo docker rm -f project-please-back_app_flask_1
            sudo docker rm -f project-please-back_app_spring_1
            sudo docker image prune -af
            sudo docker volume prune -af
            sudo docker-compose -f ~/project-please-back/docker-compose.yml up -d
